manifest:
  remotes:
    - name: andrewpreston
      url-base: https://github.com/aprest10
  projects:
    - name: zmk
      remote: andrewpreston
      revision: main
      import: config/west.yml
  self:
    path: config
