manifest:
  remotes:
    - name: aprest10
      url-base: https://github.com/aprest10
  projects:
    - name: zmk
      remote: aprest10
      revision: main
      import: config/west.yml
  self:
    path: config
